### ISSUE TITLE
Typo su pagina video corso

### ISSUE THREAD

**Issue by mauroartizzu** [bitcoin-dalla-teoria-alla-pratica/bitcoin-in-action-playground#1]
Quale pagina contiene l'errore?
https://playground.bitcoininaction.com/video-corso-su-bitcoin

Come vorresti effettuare la correzione?
Correggere da:
"Utilizzre il playground per replicare gli argomenti del video corso"
a:
"Utilizzare il playground per replicare gli argomenti del video corso"

**Comment by alessandro-aglietti** [comment]
Top, risolto grazie!!

**Comment by mauroartizzu** [comment]
Stessa pagina, mancano gli accenti:

Per chi fosse interessato ad una specifica tematica c'e' la possibilita' di consultare i capitoli specifici senza dover acquistare l'intero bundle.

diventa:
Per chi fosse interessato ad una specifica tematica c'è la possibilità di consultare i capitoli specifici senza dover acquistare l'intero bundle.

**Comment by alessandro-aglietti** [comment]
Sul mio layout non ho le lettere accentate, per ora le lasciamo cosi' :D

**Comment by Barno** [comment]
eeeh gli accenti! lascia perdere Mauro!

**Comment by mauroartizzu** [comment]
@Barno sono attento al design <3

**Comment by Barno** [comment]
> @Barno sono attento al design <3

Baiocchi?
